### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by sbeeker** [mattscilipoti/passport_scheduler#15]
Tried to use your docker information after the RoR discussion.  On a Mac in order to do the docker-compose what is the trick?  I installed docker via brew.  Also, hate to dwell on this one.  The postgres image needs to be started I think prior to spin up of docker for the rails.  When I tried to run docker it said so.  But then,, I am not sure the docker-compose is there.

I tried to do this some months back and found I needed some other docker server and at that time I came to conclusion the Mac did not support docker as the server.  So am missing something in getting started.

If you were on a mac and did this from scratch.  "brew install docker" than I can run your ready?  Or am I missing something.  Than I am not sure how to spin up the postures.  If you got moment to explain.

**Comment by mattscilipoti** [comment]
These instructions require the native install of Docker.  This link is in the readme: https://docs.docker.com/engine/installation/.  I have updated the instructions to clarify this.  I feel confident that you can use this Dockerfile and docker-compose.yml with the homebrew docker, but not as simply as these instructions.
